kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-argocd-cluster-argocd-application-controller-patch-operator
rules:
  - apiGroups:
      - redhatcop.redhat.io
    resources:
      - patches
    verbs:
      - update
      - create
      - list
      - delete
      - patch
  # Patch operator:
  # The lookup function, if used by the template, is executed with a client which impersonates the user 
  # issuing the object creation/update request. This should prevent security permission leakage.
  #
  # This means argocd app controller SA will need to be apple to CRUD machinesets
  - apiGroups:
      - machine.openshift.io
    resources:
      - machinesets
    verbs:
      - update
      - create
      - list
      - delete
      - patch
