# Source: https://github.com/redhat-cop/patch-operator/blob/main/config/operatorhub/operator.yaml
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: patch-operator 
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: patch-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: patch-operator 
spec:
  targetNamespaces: []