apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    "redhat-cop.redhat.io/patch": |
      metadata:
        labels:
          machine.openshift.io/cluster-api-cluster: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName
      spec:
        selector:
          matchLabels:
            machine.openshift.io/cluster-api-cluster: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName" }}
            machine.openshift.io/cluster-api-machineset: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName" }}-storage
        template:
          spec:
            providerSpec:
              value:
                network:
                  devices:
                  - networkName: {{ (lookup "v1" "ConfigMap" "kube-system" "cluster-config-v1").data.install-config.platform.vsphere.network" }}
                template: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName" }}-rhcos
                workspace:
                  datacenter: {{ (lookup "v1" "ConfigMap" "kube-system" "cluster-config-v1").data.install-config.platform.vsphere.datacenter" }}
                  datastore: {{ (lookup "v1" "ConfigMap" "kube-system" "cluster-config-v1").data.install-config.platform.vsphere.defaultDatastore" }}
                  folder: {{ (lookup "v1" "ConfigMap" "kube-system" "cluster-config-v1").data.install-config.platform.vsphere.folder" }}
                  resourcePool: {{ (lookup "v1" "ConfigMap" "kube-system" "cluster-config-v1").data.install-config.platform.vsphere.resourcePool" }}
                  server: {{ (lookup "v1" "ConfigMap" "kube-system" "cluster-config-v1").data.install-config.platform.vsphere.vCenter" }}
  labels:
    machine.openshift.io/cluster-api-cluster: << infrastructureId >>
    machine.openshift.io/cluster-api-machine-role: storage
    machine.openshift.io/cluster-api-machine-type: storage
  name: ocpinstall-storage
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: << infrastructureId >>
      machine.openshift.io/cluster-api-machineset: << infrastructureId >>-storage
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: << infrastructureId >>
        machine.openshift.io/cluster-api-machine-role: storage
        machine.openshift.io/cluster-api-machine-type: storage
        machine.openshift.io/cluster-api-machineset: << infrastructureId >>-storage
    spec:
      taints:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        value: "true"
      metadata:
        labels:
          cluster.ocs.openshift.io/openshift-storage: ""
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: VSphereMachineProviderSpec
          memoryMiB: 65536
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: << networkName >>
          numCPUs: 16
          numCoresPerSocket: 1
          snapshot: ""
          template: {{ $.Values.infrastructureId }}-rhcos
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: IBMCloud
            datastore: gym-50b01ssfct-oumd6mga-storage
            folder: /IBMCloud/vm/ocpinstall-p2g95
            resourcePool: /IBMCloud/host/ocp-gym/Resources
            server: ocpgym-vc.techzone.ibm.local