---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: patch-operator-inject
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: patch-operator-controller-manager-service
      namespace: patch-operator
      path: /inject
    caBundle: Cg==
  failurePolicy: Fail
  name: patch-operator-inject.redhatcop.redhat.io
  rules:
  - apiGroups:
    - machine.openshift.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    resources:
    - machinesets
  sideEffects: None